{
        'type': 'game', // game or console
        'name': 'Asteroids',
        'authors': ['Lyle Rains ', 'Ed Logg'],
        'company': ['Atári'],  
        'year': '1979',
        'headline': 'A história do jogo asteroids',
        'resume': [
            'Asteroids é um jogo de arcade com gráficos vetoriais ',
            'muito popular lançado em 1981 pela Atari. ',
            'O objetivo do jogo é destruir asteroides ',
            'sem se deixar ser atingido por seus fragmentos. ',
            'O jogo apresentava visual simples, sem cores ',
            'e nem padrões muito ousados ou músicas, se apoiando ',
            'penas em sua jogabilidade viciante.',
        ].join(''),
        'full_text': [
            'Asteroids é um arcade space shooter lançado em novembro de 1979 pela Atári.',
            'O jogador controla uma nave espacial em um campo de asteróides ',
            'que periodicamente encontra com discos voadores. O objetivo do jogo ',
            'é atirar e destruir asteróides e os discos, e não colidir ',
            'com nenhum, ou ser atingido por tiros dos discos inimigos.',
            'O jogo se torna mais difícil quando o número de asteróides aumenta. ',
            'Asteroids foi implementado em hardware desenvolvido por Howard Delman ',
            'desenhadas em um monitor de vetor. ',
            'Rains inicialmente queria que o jogo feito em Bitmap, ',
            'mas Logg, com experiência em gráficos vetoriais, ',
            'sugeriu um monitor de XY porque a resolução 1024x760 alta permitiria uma mira precisa. ',
            'Os dois discos foram formuladas para serem diferentes um do outro. ',
            'Um temporizador constante que diminui os intervalos entre os ataques ',
            'dos discos foi empregado para evitar de o jogador disparar em asteróides e discos. ',
            'A trilha sonora minimalista apresenta uma efeito sonoro de "pulsação", ',
            'o que acelera conforme o jogo progride. ',
            'Asteroids era extremamente viciante pela sua jogabilidade ',
            'simples e desafios empolgantes. ',
            'Não era incomum na época do game ver os arcades lotados de crianças ',
            'que tentavam quebrar recordes de pontuação. ',
            'E nem os funcionários da Atari deixavam de jogar ',
            'dentro da empresa quando tinham um momento de folga. '.
        ].join(''),
        'thumbnail': 'thumbnail.png',
        'main_img': 'mainimage.png',
        'images': ['picture.png', 'picture1.png'],
        'video_gameplay': ['https://www.youtube.com/watch?v=cZfsnA7dAHI'],
        'references': ['http://www.gameblast.com.br/2014/04/relembre-o-classico-asteroids-um.html', 
            'http://en.wikipedia.org/wiki/Asteroids_(video_game)',
            'http://pt.wikipedia.org/wiki/Asteroids']
}
